<?php
/**
 * AudioTracks
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  ThisIsDevelopment\OpenApi\Bol\Retailer
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * v9 - Retailer API
 *
 * The bol.com API for retailers.  # Authentication Our API requires authentication via OAuth2. The detailed steps to authenticate are explained [here](https://api.bol.com/retailer/public/Retailer-API/authentication.html)   # Demo scenarios Our API specification includes examples of the responses you can expect. For more information as well as more examples, we refer you to the following resources:   - [Demo environment](https://api.bol.com/retailer/public/Retailer-API/demo/demo.html) - [Demo scenarios](https://api.bol.com/retailer/public/Retailer-API/demo/v9-index.html)
 *
 * The version of the OpenAPI document: 9.x
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ThisIsDevelopment\OpenApi\Bol\Retailer\Models;

use \ArrayAccess;
use \ThisIsDevelopment\OpenApi\Bol\Retailer\ObjectSerializer;

/**
 * AudioTracks Class Doc Comment
 *
 * @category Class
 * @package  ThisIsDevelopment\OpenApi\Bol\Retailer
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class AudioTracks implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'AudioTracks';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'discNumber' => 'string',
        'trackNumber' => 'string',
        'discSide' => 'string',
        'title' => 'string',
        'artistName' => 'string',
        'playTime' => 'string',
        'clipUrl' => 'string',
        'clipType' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'discNumber' => null,
        'trackNumber' => null,
        'discSide' => null,
        'title' => null,
        'artistName' => null,
        'playTime' => null,
        'clipUrl' => null,
        'clipType' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'discNumber' => false,
        'trackNumber' => false,
        'discSide' => false,
        'title' => false,
        'artistName' => false,
        'playTime' => false,
        'clipUrl' => false,
        'clipType' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'discNumber' => 'discNumber',
        'trackNumber' => 'trackNumber',
        'discSide' => 'discSide',
        'title' => 'title',
        'artistName' => 'artistName',
        'playTime' => 'playTime',
        'clipUrl' => 'clipUrl',
        'clipType' => 'clipType'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'discNumber' => 'setDiscNumber',
        'trackNumber' => 'setTrackNumber',
        'discSide' => 'setDiscSide',
        'title' => 'setTitle',
        'artistName' => 'setArtistName',
        'playTime' => 'setPlayTime',
        'clipUrl' => 'setClipUrl',
        'clipType' => 'setClipType'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'discNumber' => 'getDiscNumber',
        'trackNumber' => 'getTrackNumber',
        'discSide' => 'getDiscSide',
        'title' => 'getTitle',
        'artistName' => 'getArtistName',
        'playTime' => 'getPlayTime',
        'clipUrl' => 'getClipUrl',
        'clipType' => 'getClipType'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('discNumber', $data ?? [], null);
        $this->setIfExists('trackNumber', $data ?? [], null);
        $this->setIfExists('discSide', $data ?? [], null);
        $this->setIfExists('title', $data ?? [], null);
        $this->setIfExists('artistName', $data ?? [], null);
        $this->setIfExists('playTime', $data ?? [], null);
        $this->setIfExists('clipUrl', $data ?? [], null);
        $this->setIfExists('clipType', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets discNumber
     *
     * @return string|null
     */
    public function getDiscNumber()
    {
        return $this->container['discNumber'];
    }

    /**
     * Sets discNumber
     *
     * @param string|null $discNumber The disc number within an album the audio track is stored on.
     *
     * @return self
     */
    public function setDiscNumber($discNumber)
    {
        if (is_null($discNumber)) {
            throw new \InvalidArgumentException('non-nullable discNumber cannot be null');
        }
        $this->container['discNumber'] = $discNumber;

        return $this;
    }

    /**
     * Gets trackNumber
     *
     * @return string|null
     */
    public function getTrackNumber()
    {
        return $this->container['trackNumber'];
    }

    /**
     * Sets trackNumber
     *
     * @param string|null $trackNumber The track number on the album.
     *
     * @return self
     */
    public function setTrackNumber($trackNumber)
    {
        if (is_null($trackNumber)) {
            throw new \InvalidArgumentException('non-nullable trackNumber cannot be null');
        }
        $this->container['trackNumber'] = $trackNumber;

        return $this;
    }

    /**
     * Gets discSide
     *
     * @return string|null
     */
    public function getDiscSide()
    {
        return $this->container['discSide'];
    }

    /**
     * Sets discSide
     *
     * @param string|null $discSide The disc side on which the audio track is stored on.
     *
     * @return self
     */
    public function setDiscSide($discSide)
    {
        if (is_null($discSide)) {
            throw new \InvalidArgumentException('non-nullable discSide cannot be null');
        }
        $this->container['discSide'] = $discSide;

        return $this;
    }

    /**
     * Gets title
     *
     * @return string|null
     */
    public function getTitle()
    {
        return $this->container['title'];
    }

    /**
     * Sets title
     *
     * @param string|null $title The title of the audio track.
     *
     * @return self
     */
    public function setTitle($title)
    {
        if (is_null($title)) {
            throw new \InvalidArgumentException('non-nullable title cannot be null');
        }
        $this->container['title'] = $title;

        return $this;
    }

    /**
     * Gets artistName
     *
     * @return string|null
     */
    public function getArtistName()
    {
        return $this->container['artistName'];
    }

    /**
     * Sets artistName
     *
     * @param string|null $artistName The name of the artist(s) performing the audio track.
     *
     * @return self
     */
    public function setArtistName($artistName)
    {
        if (is_null($artistName)) {
            throw new \InvalidArgumentException('non-nullable artistName cannot be null');
        }
        $this->container['artistName'] = $artistName;

        return $this;
    }

    /**
     * Gets playTime
     *
     * @return string|null
     */
    public function getPlayTime()
    {
        return $this->container['playTime'];
    }

    /**
     * Sets playTime
     *
     * @param string|null $playTime The play time of the audio track.
     *
     * @return self
     */
    public function setPlayTime($playTime)
    {
        if (is_null($playTime)) {
            throw new \InvalidArgumentException('non-nullable playTime cannot be null');
        }
        $this->container['playTime'] = $playTime;

        return $this;
    }

    /**
     * Gets clipUrl
     *
     * @return string|null
     */
    public function getClipUrl()
    {
        return $this->container['clipUrl'];
    }

    /**
     * Sets clipUrl
     *
     * @param string|null $clipUrl The URL on which an audio clip of the audio track has been made available.
     *
     * @return self
     */
    public function setClipUrl($clipUrl)
    {
        if (is_null($clipUrl)) {
            throw new \InvalidArgumentException('non-nullable clipUrl cannot be null');
        }
        $this->container['clipUrl'] = $clipUrl;

        return $this;
    }

    /**
     * Gets clipType
     *
     * @return string|null
     */
    public function getClipType()
    {
        return $this->container['clipType'];
    }

    /**
     * Sets clipType
     *
     * @param string|null $clipType The format in which the audio clip is available.
     *
     * @return self
     */
    public function setClipType($clipType)
    {
        if (is_null($clipType)) {
            throw new \InvalidArgumentException('non-nullable clipType cannot be null');
        }
        $this->container['clipType'] = $clipType;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


