<?php
/**
 * RetailerRating
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  ThisIsDevelopment\OpenApi\Bol\Retailer
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * v9 - Retailer API
 *
 * The bol.com API for retailers.  # Authentication Our API requires authentication via OAuth2. The detailed steps to authenticate are explained [here](https://api.bol.com/retailer/public/Retailer-API/authentication.html)   # Demo scenarios Our API specification includes examples of the responses you can expect. For more information as well as more examples, we refer you to the following resources:   - [Demo environment](https://api.bol.com/retailer/public/Retailer-API/demo/demo.html) - [Demo scenarios](https://api.bol.com/retailer/public/Retailer-API/demo/v9-index.html)
 *
 * The version of the OpenAPI document: 9.x
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ThisIsDevelopment\OpenApi\Bol\Retailer\Models;

use \ArrayAccess;
use \ThisIsDevelopment\OpenApi\Bol\Retailer\ObjectSerializer;

/**
 * RetailerRating Class Doc Comment
 *
 * @category Class
 * @description Rating on different aspects all being one decimal precision.
 * @package  ThisIsDevelopment\OpenApi\Bol\Retailer
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class RetailerRating implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'RetailerRating';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'retailerRating' => 'float',
        'productInformationRating' => 'float',
        'deliveryTimeRating' => 'float',
        'shippingRating' => 'float',
        'serviceRating' => 'float'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'retailerRating' => 'double',
        'productInformationRating' => 'double',
        'deliveryTimeRating' => 'double',
        'shippingRating' => 'double',
        'serviceRating' => 'double'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'retailerRating' => false,
        'productInformationRating' => false,
        'deliveryTimeRating' => false,
        'shippingRating' => false,
        'serviceRating' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'retailerRating' => 'retailerRating',
        'productInformationRating' => 'productInformationRating',
        'deliveryTimeRating' => 'deliveryTimeRating',
        'shippingRating' => 'shippingRating',
        'serviceRating' => 'serviceRating'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'retailerRating' => 'setRetailerRating',
        'productInformationRating' => 'setProductInformationRating',
        'deliveryTimeRating' => 'setDeliveryTimeRating',
        'shippingRating' => 'setShippingRating',
        'serviceRating' => 'setServiceRating'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'retailerRating' => 'getRetailerRating',
        'productInformationRating' => 'getProductInformationRating',
        'deliveryTimeRating' => 'getDeliveryTimeRating',
        'shippingRating' => 'getShippingRating',
        'serviceRating' => 'getServiceRating'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('retailerRating', $data ?? [], null);
        $this->setIfExists('productInformationRating', $data ?? [], null);
        $this->setIfExists('deliveryTimeRating', $data ?? [], null);
        $this->setIfExists('shippingRating', $data ?? [], null);
        $this->setIfExists('serviceRating', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['retailerRating'] === null) {
            $invalidProperties[] = "'retailerRating' can't be null";
        }
        if (($this->container['retailerRating'] > 10)) {
            $invalidProperties[] = "invalid value for 'retailerRating', must be smaller than or equal to 10.";
        }

        if (($this->container['retailerRating'] < 1)) {
            $invalidProperties[] = "invalid value for 'retailerRating', must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['productInformationRating']) && ($this->container['productInformationRating'] > 10)) {
            $invalidProperties[] = "invalid value for 'productInformationRating', must be smaller than or equal to 10.";
        }

        if (!is_null($this->container['productInformationRating']) && ($this->container['productInformationRating'] < 1)) {
            $invalidProperties[] = "invalid value for 'productInformationRating', must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['deliveryTimeRating']) && ($this->container['deliveryTimeRating'] > 10)) {
            $invalidProperties[] = "invalid value for 'deliveryTimeRating', must be smaller than or equal to 10.";
        }

        if (!is_null($this->container['deliveryTimeRating']) && ($this->container['deliveryTimeRating'] < 1)) {
            $invalidProperties[] = "invalid value for 'deliveryTimeRating', must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['shippingRating']) && ($this->container['shippingRating'] > 10)) {
            $invalidProperties[] = "invalid value for 'shippingRating', must be smaller than or equal to 10.";
        }

        if (!is_null($this->container['shippingRating']) && ($this->container['shippingRating'] < 1)) {
            $invalidProperties[] = "invalid value for 'shippingRating', must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['serviceRating']) && ($this->container['serviceRating'] > 10)) {
            $invalidProperties[] = "invalid value for 'serviceRating', must be smaller than or equal to 10.";
        }

        if (!is_null($this->container['serviceRating']) && ($this->container['serviceRating'] < 1)) {
            $invalidProperties[] = "invalid value for 'serviceRating', must be bigger than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets retailerRating
     *
     * @return float
     */
    public function getRetailerRating()
    {
        return $this->container['retailerRating'];
    }

    /**
     * Sets retailerRating
     *
     * @param float $retailerRating General rating of the retailer.
     *
     * @return self
     */
    public function setRetailerRating($retailerRating)
    {
        if (is_null($retailerRating)) {
            throw new \InvalidArgumentException('non-nullable retailerRating cannot be null');
        }

        if (($retailerRating > 10)) {
            throw new \InvalidArgumentException('invalid value for $retailerRating when calling RetailerRating., must be smaller than or equal to 10.');
        }
        if (($retailerRating < 1)) {
            throw new \InvalidArgumentException('invalid value for $retailerRating when calling RetailerRating., must be bigger than or equal to 1.');
        }

        $this->container['retailerRating'] = $retailerRating;

        return $this;
    }

    /**
     * Gets productInformationRating
     *
     * @return float|null
     */
    public function getProductInformationRating()
    {
        return $this->container['productInformationRating'];
    }

    /**
     * Sets productInformationRating
     *
     * @param float|null $productInformationRating Product rating of the retailer.
     *
     * @return self
     */
    public function setProductInformationRating($productInformationRating)
    {
        if (is_null($productInformationRating)) {
            throw new \InvalidArgumentException('non-nullable productInformationRating cannot be null');
        }

        if (($productInformationRating > 10)) {
            throw new \InvalidArgumentException('invalid value for $productInformationRating when calling RetailerRating., must be smaller than or equal to 10.');
        }
        if (($productInformationRating < 1)) {
            throw new \InvalidArgumentException('invalid value for $productInformationRating when calling RetailerRating., must be bigger than or equal to 1.');
        }

        $this->container['productInformationRating'] = $productInformationRating;

        return $this;
    }

    /**
     * Gets deliveryTimeRating
     *
     * @return float|null
     */
    public function getDeliveryTimeRating()
    {
        return $this->container['deliveryTimeRating'];
    }

    /**
     * Sets deliveryTimeRating
     *
     * @param float|null $deliveryTimeRating Delivery rating of the retailer.
     *
     * @return self
     */
    public function setDeliveryTimeRating($deliveryTimeRating)
    {
        if (is_null($deliveryTimeRating)) {
            throw new \InvalidArgumentException('non-nullable deliveryTimeRating cannot be null');
        }

        if (($deliveryTimeRating > 10)) {
            throw new \InvalidArgumentException('invalid value for $deliveryTimeRating when calling RetailerRating., must be smaller than or equal to 10.');
        }
        if (($deliveryTimeRating < 1)) {
            throw new \InvalidArgumentException('invalid value for $deliveryTimeRating when calling RetailerRating., must be bigger than or equal to 1.');
        }

        $this->container['deliveryTimeRating'] = $deliveryTimeRating;

        return $this;
    }

    /**
     * Gets shippingRating
     *
     * @return float|null
     */
    public function getShippingRating()
    {
        return $this->container['shippingRating'];
    }

    /**
     * Sets shippingRating
     *
     * @param float|null $shippingRating Shipping rating of the retailer.
     *
     * @return self
     */
    public function setShippingRating($shippingRating)
    {
        if (is_null($shippingRating)) {
            throw new \InvalidArgumentException('non-nullable shippingRating cannot be null');
        }

        if (($shippingRating > 10)) {
            throw new \InvalidArgumentException('invalid value for $shippingRating when calling RetailerRating., must be smaller than or equal to 10.');
        }
        if (($shippingRating < 1)) {
            throw new \InvalidArgumentException('invalid value for $shippingRating when calling RetailerRating., must be bigger than or equal to 1.');
        }

        $this->container['shippingRating'] = $shippingRating;

        return $this;
    }

    /**
     * Gets serviceRating
     *
     * @return float|null
     */
    public function getServiceRating()
    {
        return $this->container['serviceRating'];
    }

    /**
     * Sets serviceRating
     *
     * @param float|null $serviceRating Service rating of the retailer.
     *
     * @return self
     */
    public function setServiceRating($serviceRating)
    {
        if (is_null($serviceRating)) {
            throw new \InvalidArgumentException('non-nullable serviceRating cannot be null');
        }

        if (($serviceRating > 10)) {
            throw new \InvalidArgumentException('invalid value for $serviceRating when calling RetailerRating., must be smaller than or equal to 10.');
        }
        if (($serviceRating < 1)) {
            throw new \InvalidArgumentException('invalid value for $serviceRating when calling RetailerRating., must be bigger than or equal to 1.');
        }

        $this->container['serviceRating'] = $serviceRating;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


